service: recycle
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_LOCATION_TABLE: ${self:service}-locationTable-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-locationTable-${sls:stage}
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createLocation:
    handler: src/locations/createLocation/createLocation.httpPostHandler
    events:
      - httpApi:
          path: /
          method: post
resources:
  Resources:
    LocationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-locationTable-${sls:stage}
